from patternCount import patternCount

trial = "ACAGGAAAAACAAAAGAACAAAAGACAGGAAAACGGCCGCACGGCCGCAACAAAAGAACAAAAGACGGCCGCAACAAAAGGTGCTCACTACGGCCGCATGTATGGTAGTGCTCACTACAGGAAAATGTATGGTAATGTATGGTAACAGGAAAACAGGAAAAACAAAAGAACAAAAGATGTATGGTAACGGCCGCACGGCCGCATGTATGGTAACGGCCGCGTGCTCACTACAGGAAAGTGCTCACTACGGCCGCATGTATGGTAACGGCCGCATGTATGGTAGTGCTCACTATGTATGGTAATGTATGGTAATGTATGGTAACAGGAAAAACAAAAGACAGGAAAGTGCTCACTACAGGAAAACGGCCGCACAGGAAAACAGGAAAACAGGAAAATGTATGGTAGTGCTCACTGTGCTCACTGTGCTCACTAACAAAAGACGGCCGCACAGGAAAACGGCCGCACGGCCGCATGTATGGTAACGGCCGCACGGCCGCACAGGAAAACGGCCGCACAGGAAAGTGCTCACTAACAAAAGACAGGAAAGTGCTCACTGTGCTCACTATGTATGGTAAACAAAAGATGTATGGTAAACAAAAGACGGCCGCGTGCTCACTATGTATGGTAATGTATGGTAATGTATGGTAACGGCCGCACGGCCGCATGTATGGTAACAGGAAAACAGGAAAGTGCTCACTACGGCCGCACAGGAAAATGTATGGTAACAGGAAAGTGCTCACTATGTATGGTAACGGCCGCATGTATGGTAATGTATGGTAACGGCCGCGTGCTCACTACAGGAAAACAGGAAAAACAAAAGGTGCTCACTGTGCTCACTATGTATGGTAACAGGAAAATGTATGGTAAACAAAAGGTGCTCACTAACAAAAGAACAAAAGACGGCCGCATGTATGGTAGTGCTCACTAACAAAAG"
kmer = 13

def frequentWords(text, k):
    frequentPatterns = []
    count = []
    for x in range(0, len(text) - k + 1):
        pattern = text[x: k + x]
        count.append(patternCount(text, pattern))
        
    maxCount = max(count)
    for x in range(0, len(text) - k + 1):
        if count[x] == maxCount:
            frequentPatterns.append(text[x : k + x])
    frequentPatterns = list(dict.fromkeys(frequentPatterns))
    return frequentPatterns

print(frequentWords(trial, kmer))